apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: my-app

profiles:
  - name: dev
    manifests:
      rawYaml:
        - cloudrun-service.yaml
    deploy:
      cloudrun:
        projectid: kiran-497505
        region: asia-south1

  - name: staging
    manifests:
      rawYaml:
        - cloudrun-service.yaml
    deploy:
      cloudrun:
        projectid: kiran-497505
        region: asia-south1

  - name: prod
    manifests:
      rawYaml:
        - cloudrun-service.yaml
    deploy:
      cloudrun:
        projectid: kiran-497505
        region: asia-south1
